# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: clave-indexer
description: Clave Balances Indexer
networks:
  - id: 324
    start_block: 9767
    contracts:
      - name: ERC20 # Both for ERC20Transfer and Venus
        handler: src/ERC20Handler.ts
        events:
          - event: "Transfer(address indexed from, address indexed to, uint256 value)"
      - name: SyncswapFactory
        handler: src/SyncswapHandler.ts
        address:
          - 0xf2DAd89f2788a8CD54625C60b55cD3d2D0ACa7Cb
          - 0x5b9f21d407F35b10CbfDDca17D5D84b129356ea3
          - 0x0a34FBDf37C246C0B401da5f00ABd6529d906193
          - 0x81251524898774F5F2FCaE7E7ae86112Cb5C317f
          - 0x20b28B1e4665FFf290650586ad76E977EAb90c5D
          - 0x0754870C1aAb00eDCFABDF4e6FEbDD30e90f327d
        events:
          - event: "PoolCreated(address indexed token0, address indexed token1, address pool)"
      - name: SyncswapPool
        handler: src/SyncswapHandler.ts
        events:
          - event: "Sync(uint reserve0, uint reserve1)"
            field_selection:
              transaction_fields:
                - "from"
          - event: "Mint(address indexed sender, uint amount0, uint amount1, uint liquidity, address indexed to)"
            field_selection:
              transaction_fields:
                - "from"
          - event: "Burn(address indexed sender, uint amount0, uint amount1, uint liquidity, address indexed to)"
            field_selection:
              transaction_fields:
                - "from"
      - name: Aave
        handler: src/AaveHandler.ts
        address:
          - 0xE977F9B2a5ccf0457870a67231F23BE4DaecfbDb
          - 0xC48574bc5358c967d9447e7Df70230Fdb469e4E7
          - 0xb7b93bCf82519bB757Fd18b23A389245Dbd8ca64
          - 0xd4e607633F3d984633E946aEA4eb71f92564c1c9
          - 0xd6cD2c0fC55936498726CacC497832052A9B2D1B
        events:
          - event: "Mint(address indexed caller, address indexed onBehalfOf, uint256 value, uint256 balanceIncrease, uint256 index)"
          - event: "Burn(address indexed from, address indexed target, uint256 value, uint256 balanceIncrease, uint256 index)"
      - name: Venus
        handler: src/VenusHandler.ts
        address:
          - 0x84064c058f2efea4ab648bb6bd7e40f83ffde39a
          - 0x1af23bd57c62a99c59ad48236553d0dd11e49d2d
          - 0x69cda960e3b20dfd480866fffd377ebe40bd0a46
          - 0xaf8fd83cfcbe963211faaf1847f0f217f80b4719
          - 0x1fa916c27c7c2c4602124a14c77dbb40a5ff1be8
          - 0x697a70779c1a03ba2bd28b7627a902bff831b616
        events:
          - event: "Borrow(address indexed borrower, uint256 borrowAmount, uint256 accountBorrows, uint256 totalBorrows)"
          - event: "RepayBorrow(address indexed payer, address indexed borrower, uint256 repayAmount, uint256 accountBorrows, uint256 totalBorrows)"
          - event: "AccrueInterest(uint256 cashPrior, uint256 interestAccumulated, uint256 borrowIndex, uint256 totalBorrows)"
          - event: "BadDebtIncreased(address indexed borrower, uint256 badDebtDelta, uint256 badDebtOld, uint256 badDebtNew)"
          - event: "BadDebtRecovered(uint256 badDebtOld, uint256 badDebtNew)"
      - name: ClaggMain
        handler: src/ClaggHandler.ts
        address: 0x7f73934F333a25B456Dc9B8b62A19f211c991f1c
        events:
          - event: "Deposit(address indexed user, address indexed pool, uint256 amount, uint256 shares)"
          - event: "Withdraw(address indexed user, address indexed pool, uint256 amount, uint256 shares)"

rollback_on_reorg: false
#* 9767 syncswap first block
#* 43552171 venus first block
#* 24805087 clave first block
#* 52887531 clagg first block
#* 44671523 aave first block
