# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: clave-erc20-indexer
description: Clave ERC20 Balances Indexer
networks:
  - id: 324
    start_block: 24805087
    contracts:
      - name: ERC20
        handler: src/handlers/ERC20Handler.ts
        events:
          - event: "Transfer(address indexed from, address indexed to, uint256 value)"
# Rollback on reorg mode currently incurs a performance hit on historical sync
# while developing an indexer we recommend setting this to false
rollback_on_reorg: false
